spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: true
    default-property-inclusion: non_null
  jpa:
    open-in-view: false
    properties:
      hibernate.dialect: org.hibernate.dialect.OracleDialect
      hibernate.jdbc.time_zone: UTC
    hibernate.ddl-auto: validate
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      pool-name: passkey-pool
  data:
    redis:
      lettuce:
        pool:
          enabled: true
          max-active: 8

management:
  endpoint.health.show-details: always
  endpoints.web.exposure.include: health,info
