package com.crosscert.passkey.core.entity;

import jakarta.persistence.*;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.annotations.UuidGenerator;
import org.hibernate.type.SqlTypes;

import java.time.Instant;
import java.util.UUID;

@Entity
@Table(name = "TENANT")
public class Tenant {

    @Id
    @UuidGenerator(style = UuidGenerator.Style.TIME)
    @JdbcTypeCode(SqlTypes.UUID)
    @Column(name = "ID", columnDefinition = "RAW(16)")
    private UUID id;

    @Column(name = "SLUG", length = 64, nullable = false, unique = true)
    private String slug;

    @Column(name = "DISPLAY_NAME", length = 256, nullable = false)
    private String displayName;

    @Column(name = "STATUS", length = 16, nullable = false)
    private String status;

    @Column(name = "RP_ID", length = 256, nullable = false)
    private String rpId;

    @Column(name = "RP_NAME", length = 256, nullable = false)
    private String rpName;

    @Lob
    @Column(name = "ALLOWED_ORIGINS", nullable = false)
    private String allowedOriginsJson;

    @Lob
    @Column(name = "ATTESTATION_POLICY")
    private String attestationPolicyJson;

    @Column(name = "CREATED_AT", nullable = false, updatable = false)
    private Instant createdAt;

    @Column(name = "UPDATED_AT", nullable = false)
    private Instant updatedAt;

    protected Tenant() {}

    /**
     * Convenience constructor for test fixtures and Phase 0 call sites.
     * The first argument is now slug (human-readable identifier like "acme"),
     * not the surrogate id. UUID id is auto-generated by @UuidGenerator.
     */
    public Tenant(String slug, String displayName) {
        this(slug, displayName,
             /* rpId */ "localhost",
             /* rpName */ displayName,
             /* allowedOriginsJson */ "[\"http://localhost:8080\",\"http://localhost:8082\"]",
             /* attestationPolicyJson */ "{\"acceptedFormats\":[\"none\",\"packed\",\"android-key\",\"android-safetynet\",\"fido-u2f\",\"apple\",\"tpm\"],\"requireUserVerification\":true,\"mdsRequired\":false}");
    }

    public Tenant(String slug, String displayName, String rpId, String rpName,
                  String allowedOriginsJson, String attestationPolicyJson) {
        this.slug = slug;
        this.displayName = displayName;
        this.status = "active";
        this.rpId = rpId;
        this.rpName = rpName;
        this.allowedOriginsJson = allowedOriginsJson;
        this.attestationPolicyJson = attestationPolicyJson;
        Instant now = Instant.now();
        this.createdAt = now;
        this.updatedAt = now;
    }

    public UUID getId() { return id; }
    public String getSlug() { return slug; }
    public String getDisplayName() { return displayName; }
    public String getStatus() { return status; }
    public String getRpId() { return rpId; }
    public String getRpName() { return rpName; }
    public String getAllowedOriginsJson() { return allowedOriginsJson; }
    public String getAttestationPolicyJson() { return attestationPolicyJson; }
    public Instant getCreatedAt() { return createdAt; }
    public Instant getUpdatedAt() { return updatedAt; }
}
